name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.2.app
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: xcodebuild test -scheme "Zen Tuner" -destination platform="iOS Simulator,name=iPhone 15 Pro Max,OS=17.2"
  test_packages:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.2.app
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: swift test --package-path Packages/MicrophonePitchDetector
  macos:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.2.app
    steps:
      - uses: actions/checkout@v4
      - name: Build macOS
        run: xcodebuild build -scheme "Zen Tuner" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  watchos:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.2.app
    steps:
      - uses: actions/checkout@v4
      - name: Build watchOS
        run: xcodebuild build -scheme "ZenTuner_watchOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  lint:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/realm/swiftlint:0.54.0
    steps:
      - uses: actions/checkout@v4
      - name: Run SwiftLint
        run: swiftlint lint --strict
